import { Outfit as OutfitFont, Ovo as OvoFont , Handlee } from "next/font/google";
import "./globals.css";

const Outfit = OutfitFont({
  subsets: ["latin"], weight: ["400","500","600","700"]
});
const handlee = Handlee({
  subsets: ["latin"], weight: ["400"]
});

const Ovo = OvoFont({
  subsets: ["latin"], weight: ["400"]
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Outfit.className} ${Ovo.className} ${handlee.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
